### ISSUE TITLE
"Page not Found" title in different languages

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-error#23]
Hello!

Today I found that in every language my title looks the same:

```
Page not Found — sitename
```

Maybe need to put +1 line to `languages.yaml`:

``` yaml
PLUGIN_ERROR:
    ERROR: "Error"
    ERROR_MESSAGE: "Woops. Looks like this page doesn't exist."
    ERROR_TITLE_404: "Page not found"
```

and correctly handle this?

**Comment by rbukovansky** [comment]
@Sogl @flaviocopes Hi, this should be resolved by PR #26 which I just submitted.
