### ISSUE TITLE
About error page title translation

### ISSUE THREAD

**Issue by gizmecano** [getgrav/grav-plugin-error#39]
I _reopen_ an issue concerning the translation of the title of the error pages.

Indeed, an issue about the translation of the page title string was opened previously in 2016 by @Sogl (cf.  #23) but was closed in 2018.

The pull request which had been envisaged by @rbukovansky (cf. #26) doesn't seem to have been finally retained (it was reverted by @rhukster in e06ca063524f24039ef1339b240f302bdf9cab54).

However, the issue seems still unsolved at the moment or maybe I missed the key solution to properly translate this `page.title` variable within an error page...

PS : Of course, you may directly close this present issue and reopen the previous one if you consider the original issue as still relevant.

**Comment by ricardo118** [comment]
I looked at the old PR and made a new PR that solves this:

https://github.com/getgrav/grav-plugin-error/pull/40

Please note that this only adds the translated title (same way the header is built on the page) to the built in error page. If you provide a custom error page, it will not override its title.

**Comment by gizmecano** [comment]
Hi @ricardo118,

> Please note that this only adds the translated title (same way the header is built on the page) to the built in error page. If you provide a custom error page, it will not override its title.

IMHO, I think this change should be more than enough in most cases. Thank you for dealing with this issue so quickly.

I hope that this new pull request #40 will be approved this time.

**Comment by mahagr** [comment]
Pull request was merged. :)

**Comment by gizmecano** [comment]
> Pull request was merged. :)

Minor question (because I am not aware of your team workflow): is there any code review process to do before expecting the release of a new version that will include this merged change?

**Comment by ricardo118** [comment]
@gizmecano pull requests get automatically released all together as new releases come out, youcan however run these changes in your environment without issues

**Comment by gizmecano** [comment]
Well, I was inclined to thought something like that.
Thank you for this clear explanation.

**Comment by gizmecano** [comment]
As this issue was merged by @rhukster in 1fa18a7266d910f2110f6f119bdd207d56503d9b , I suppose that it can now be closed. Thanks.
